### ISSUE TITLE
Timeline request returns `paging` as array

### ISSUE THREAD

**Issue by njkleiner** [aaronpk/Aperture#101]
When making a timeline request for an empty channel, the `paging` property returned is an empty array, rather than an empty object.

This makes it impossible to parse the response in some circumstances where the `paging` property is expected to always have the same type (i.e., JSON object).

```
$ curl -i -H "Authorization: Bearer <redacted>" "https://aperture.p3k.io/microsub/452?action=timeline&channel=2PkyeIadiaLZXnMVYdJVh7w7"

HTTP/2 200 
server: nginx/1.14.0
content-type: application/json
x-powered-by: PHP/7.2.7-1+ubuntu16.04.1+deb.sury.org+1
cache-control: no-cache, private
date: Sat, 30 Jan 2021 21:08:25 GMT

{"items":[],"paging":[]}
```

**Comment by aaronpk** [comment]
ah thanks, weird PHP thing! I will fix it.

**Comment by njkleiner** [comment]
> ah thanks, weird PHP thing! I will fix it.

Thanks for the quick response!

I would've sent a sent a PR, but I don't have PHP set up on my local machine.
