### ISSUE TITLE
get_channels should not return default or notifications

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/Aperture#16]
According to https://indieweb.org/Microsub-spec#Channels_2:

> The response will contain a channels property with the list of channel uids and names. The uid=default and uid=notifications channels are not part of this response, so for users who have only the default channels, the response will be an empty array.

Currently, Aperture returns all of the channels, including the default and notification channels

**Comment by aaronpk** [comment]
Good catch. But now I'm reconsidering why that restriction was there in the first place. As a client developer, would you prefer to get the full list in the response?

**Comment by EdwardHinkle** [comment]
Hmmm well I see pros and cons.

Pros:
- In Indigenous, the notifications channel will be an icon you select, not a channel in the list. Thus, it's useful to just know that channel will always exist in every Microsub client and I don't have to hard-code the removal from the returned array.

Cons:
- That leaves localization of Home and Notifications to the client, but not any of the channels names. If the Microsub server returns home and notifications in the list, the Microsub server can be responsible for that localization.

I guess in the end, I would rather pull `uid=notifications` out of the array rather than having to deal with localization of just two channels when the other will come automatically.

**Comment by aaronpk** [comment]
This brings up another issue. If these channels are not part of the response, then that also means the order of them can't be changed. Is your plan for the "notifications" channel to exist sort of outside the main list of channels? That would be a good argument for not being able to order it, since it wouldn't exist in the same list.

**Comment by EdwardHinkle** [comment]
Yeah, my plan IS to have notifications outside of the main list of channels. In my mind, I don't really see a usefulness to sorting Home and Notifications. I feel like if they are in the same list, that they should be at the top... but maybe that is a biased opinion.

That said, I guess if you have a list of sortable items, it is probably odd if there are one or two that you can't sort (home/notifications). I guess one of the big questions is: Is there anyone who has an opinion on when/why you would want to sort Home/Notifications rather than having them listed at the top of the list (or outside the list).

**Comment by EdwardHinkle** [comment]
I wonder if we should branch this into an issue on the microsub page? Seems like we are beginning to be more focused on microsub than Aperture now :)
