### ISSUE TITLE
New Channel gets sort 0, which messes with notifications

### ISSUE THREAD

**Issue by EdwardHinkle** [aaronpk/Aperture#19]
When creating a new channel now, it gets sort order 0. That leads to both the Notifications Channel and the new Channel being sort order 0 and when you try to order the new channel down one, it moves the one beneath it up to 0 and it gets stuck.

Recommendation: New Channels get placed at the bottom.

Alternate Suggestion: New Channel gets sort 1, and all other channels have to get moved down by 1.

**Comment by aaronpk** [comment]
🤦‍♂️ Thanks. I think I'll add new channels to the top!
