### ISSUE TITLE
Feed Parsing Issue

### ISSUE THREAD

**Issue by grantcodes** [aaronpk/Aperture#20]
Dunno if you want a different issue for any feed parsing issue I run into or a single issue with a list of problematic feeds.

Anyway [https://miklb.com/](https://miklb.com/) is not picking up an author property although it does seem to work with the [php mf2 parser](https://php.microformats.io/?url=https%3A%2F%2Fmiklb.com%2Fblog%2F2018%2F02%2F12%2F3430%2F)

**Comment by aaronpk** [comment]
Right now, Aperture only parses data on the feed page itself, not the permalink. There is no author property on the feed https://php.microformats.io/?url=https%3A%2F%2Fmiklb.com%2F

**Comment by grantcodes** [comment]
Yeah realised that would probably be the issue after I submitted the issue. Maybe post author data should fall back to homepage author data?

**Comment by aaronpk** [comment]
That's a question for the authorship algorithm: https://indieweb.org/authorship#How_to_determine which is actually implemented in XRay, not here.

I am planning on making some sort of feed source info available to clients as a fallback, see https://github.com/indieweb/microsub/issues/13 for more info.

**Comment by aaronpk** [comment]
Closing this issue and will continue the discussion on the authorship algorithm. https://indieweb.org/authorship#list-of-h-entrys-with-h-card If the algorithm ends up being updated, that change will be made in [XRay](https://github.com/aaronpk/XRay) anyway, which will trickle back up to here.
