### ISSUE TITLE
"No feeds were found" at URL of Atom feed

### ISSUE THREAD

**Issue by martymcguire** [aaronpk/Aperture#23]
When attempting to add http://audreywatters.com/feed.xml to a channel, Aperture responds that no feeds were found at that URL, which is itself a feed.

Standalone XRay reports that it is a feed and finds content there: https://xray.p3k.io/parse?url=http%3A%2F%2Faudreywatters.com%2Ffeed.xml

**Comment by aaronpk** [comment]
This is actually an XRay bug!

**Comment by aaronpk** [comment]
Done! you'll need to pull the new source then run `composer install`

**Comment by martymcguire** [comment]
Ahh, thanks! So fast!
