### ISSUE TITLE
Deleting channels returning 500 errors

### ISSUE THREAD

**Issue by grantcodes** [aaronpk/Aperture#3]
Trying to delete a channel I keep getting a 500 error with a html page (not json) saying "Whoops, looks like something went wrong."

I think the post request looks fine. Just been trying in [Postman](https://www.getpostman.com/). 

![image](https://user-images.githubusercontent.com/3390268/34582355-789bdb72-f18b-11e7-9f01-f9e7efc4f8cb.png)

**Comment by aaronpk** [comment]
I believe this is fixed now. Can you verify?

**Comment by grantcodes** [comment]
Yep definitely working now 👍
