### ISSUE TITLE
Support access_token for micropub endpoint

### ISSUE THREAD

**Issue by zoglesby** [aaronpk/Aperture#33]
I should start by saying this is because I am lazy. I was trying to use IFTTT to push notifications to aperture using the webhooks "channel", but they do not support adding Headers so I can't pass "Authorization: Bearer XXX", would it be possible to add support for access_token in the body as well? 

Looking at the code it seems like you are checking for Authorization: Bearer and if not returning a 401, if I am missing something please let me know.

**Comment by aaronpk** [comment]
Good call, I'll add this. I wish IFTTT would support custom headers or at least the Authorization header tho! This has been a problem for me in the past as well. Maybe if a bunch of us keep requesting it they'll eventually add it.
