### ISSUE TITLE
add IndieAuth login to channels

### ISSUE THREAD

**Issue by aaronpk** [aaronpk/Aperture#36]
Currently you can add an "API Key" in order to write content into channels. This is actually Aperture acting as a Micropub endpoint. It should be possible to log in to existing Micropub clients as one of these API keys, doing the IndieAuth flow and resulting in providing the client with the API key. This would provide a way to set up fancier integrations without copying and pasting tokens.

**Comment by EdwardHinkle** [comment]
I gave lots of wonderful emojis because this would be an awesome feature, and the reacji's needed to represent that accurately

**Comment by EdwardHinkle** [comment]
🙌🎉👍
