### ISSUE TITLE
Renaming channel fails and  creates new channel instead

### ISSUE THREAD

**Issue by grantcodes** [aaronpk/Aperture#4]
Monocle appears to be ignoring or mishandling the `channel` parameter and creates a new channel instead

Note the new uid in the screenshot below.

![image](https://user-images.githubusercontent.com/3390268/34583351-6495c288-f18f-11e7-929c-e14d74572479.png)

**Comment by aaronpk** [comment]
I'm an idiot. Apparently I hadn't pushed up some local changes that I had just done. Try again, this should be fixed now that I've actually deployed the latest code.
