### ISSUE TITLE
Feature Request: Reposts Only view

### ISSUE THREAD

**Issue by skpy** [aaronpk/Aperture#46]
Aperture allows me to exclude Reposts, Likes, etc; but it does not allow me to do the opposite: to see **only** reposts.

I follow several people on Twitter who occasionally post original Tweets, but usually just retweet other people's stuff.  I'd like the ability to follow their original posts in one channel, and dump all their retweets into another channel.  Some (sometimes, most) of their retweets are interesting and worth skimming; but I'd like to segregate them from original tweets.

I realize this may be somewhat orthogonal to the intent of Aperture, and this functionality could be handled by a different service that munges the Twitter feeds and presents new feeds to Aperture.  Feel free to close this "WONTFIX" if that's the case.

**Comment by aaronpk** [comment]
That's a use case I totally hadn't considered! Since there's already a dropdown to select certain types to only include, this is an easy change!
