### ISSUE TITLE
Event parsing lacks content & organizer

### ISSUE THREAD

**Issue by Ruxton** [aaronpk/Aperture#56]
Parsing this event http://tantek.com/2018/234/e1/homebrew-website-club-sf lead to some issues in the timeline response:

* content was missing, though summary was present
* organizer was missing
* author missing, in the single page author is present, in the homepage the entire h-feed is parented by a h-card, so I would assume if the individual event didn't have an explicit author on the homepage, it should inherit the parent h-card?

It's worth noting that the parse obviously happened using the h-feed from http://tantek.com and not the individual post. Just linked the original post so you knew where to find it.

**Comment by Ruxton** [comment]
This all boils down to https://github.com/swentel/indigenous-android rendering the event as such: 
![screenshot_20180824-115532](https://user-images.githubusercontent.com/382760/44567025-3c6bb680-a7a3-11e8-9032-a9e617c25bcb.png)

**Comment by Ruxton** [comment]
The event item in the aperture microsub response:

```
        {
            "type": "event",
            "name": "Homebrew Website Club SF!",
            "summary": "17:30: Optional writing hour and quiet socializing\n18:30: IndieWeb demos and hack night!\n\nHomebrew Website Club retro 1980s-style logo\nTopics for this week: Summer of IndieWeb! What IndieWeb projects are you hacking on this summer? 2018-09-22…23 The First IndieWebCamp Oxford! 2018-09-28…29 IndieWebCamp NYC is back for 2018 and bigger than ever!\nDemos of personal website breakthroughs. Create or update your personal web site!\nJoin a community with like-minded interests. Bring friends that want a personal site, or are interested in a healthy, independent web!\nAny questions? Ask in #indieweb Slack or IRC\nMore information: IndieWeb Wiki Event Page\nRSVP: post an indie RSVP on your own site!",
            "published": "2018-08-21 20:25-0700",
            "start": "2018-08-22 17:30-0700",
            "end": "2018-08-22 19:30-0700",
            "url": "http://tantek.com/2018/234/e1/homebrew-website-club-sf",
            "location": [
                "https://wiki.mozilla.org/SF"
            ],
            "post-type": "event",
            "refs": {
                "https://wiki.mozilla.org/SF": {
                    "type": "card",
                    "name": "Mozilla San Francisco",
                    "url": "https://wiki.mozilla.org/SF",
                    "photo": null
                }
            },
            "_id": "839580",
            "_is_read": true
        }
```

**Comment by aaronpk** [comment]
Looks like tantek has already started publishing `content` for events instead of `description`. I need to update XRay to look for that. See discussion on microformats parsing: https://github.com/microformats/h-event/issues/3

**Comment by aaronpk** [comment]
https://github.com/aaronpk/XRay/issues/75

**Comment by aaronpk** [comment]
Interesting, I don't see any reference to "author" on http://microformats.org/wiki/h-event

I suppose it makes sense to also return the author of an event. Some discussion on the vocabulary: https://github.com/microformats/h-event/issues/2#issuecomment-308650834

**Comment by aaronpk** [comment]
XRay now returns author information for events, so these posts should show up better now. The `organizer` property is still experimental/proposed in h-event, so I'm going to hold off on doing anything with that now, especially since there's no clear mapping to that in the current UI of readers.
