### ISSUE TITLE
Feeds continue to be show, even after deleted.

### ISSUE THREAD

**Issue by vipickering** [aaronpk/Aperture#66]
If I add a feed in Aperture, and look at it on Monocle. It works fine.
If I then delete the feed from Aperture, it continues to be visible in Monocle, despite it holding no data and the feed has been deleted.

Steps to re-create.

1) Add a feed. (I added https://boffosocko.com). I tried it with microformats and json same result each time.
2) View it in Monocle.
3) Go back to Aperture and delete it.
4) I still see the feed in Monocle. If I click delete entry(in Monocle) it spins and does nothing as if it gets no response from Aperture and hangs.

**Comment by aaronpk** [comment]
When you delete the feed from Aperture, it gives you two options. One is "delete and keep entries" the other is "delete and remove entries". Which one are you choosing?

**Comment by vipickering** [comment]
I have chosen "delete and remove entries"

**Comment by vipickering** [comment]
clicking on the debug option in Monocle shows this (if it helps)

`{
    "type": "entry",
    "content": {
        "text": "\u00a0Articles\n\n\n\u00a0Notes\n\n\n\u00a0Replies\n\n\n\u00a0Photos\n\n\n\u00a0Checkins\n\n\n\u00a0Audio\n\n\n\u00a0Microcast\n\n\n\u00a0Listens\n\n\n\u00a0Watches\n\n\n\u00a0RSVPs\n\n\n\u00a0Read\n\n\n\u00a0Highlights\n\n\n\u00a0Annotations\n\n\n\u00a0Favorites\n\n\n\u00a0Likes\n\n\n\u00a0Reposts\n\n\n\u00a0Bookmarks\n\n\n\u00a0Follows\n\n\n\u00a0Jams\n\n\n\u00a0Video\n\n\n\u00a0Quotes\n\n\n\u00a0Chat\n\n\n\u00a0Recipes\n\n\n\u00a0Eat\n\n\n\u00a0Drink\n\n\n\u00a0Exercise\n\n\n\u00a0Plays\n\n\n\u00a0Chickens\n\n\n\u00a0Itches\n\n\n\u00a0Issues\n\n\n\u00a0Wishlist\n\n\n\u00a0Acquisitions\n\n\n\n\n\n\u00a0Firehose\n\n\n\u00a0Microblog\n\n\n\u00a0Linkblog\n\n\n\u00a0Food Diary\n\n\n\u00a0IndieWeb Podcast\n\n\n\n\n\nI use this website as my primary hub for online presence and communication and to some extent as my online commonplace book. I try to follow the tenets of the IndieWeb movement by publishing on my own site and owning all of my own data. When I participate in social silos (Facebook, Twitter, Instagram, etc.), I post here first and syndicate duplicates out to them (POSSE). These posts either originate from here or my social stream. You\u2019re welcome to subscribe to or consume them in any manner or on any platform you prefer.\nFeatured Posts\n\n\n\n        \n                                                    \n                                                        \n                                    What I'm up to\n                                \n                            \n                                            \n                                        \n                                                    \n                                                        \n                                    An Introduction to the IndieWeb\n                                \n                            \n                                                    \n                                There's a better way to own and control your online identity\n                            \n                                            \n                                        \n                                                    \n                                                        \n                                    A Collection of IndieWeb Articles\n                                \n                            \n                                                    \n                                Here's a selection of articles and pieces I've written about IndieWeb related technology and philosophy.\n                            \n                                            \n                                        \n                                                    \n                        \n                                            \n                                        \n                                                    \n                        \n                                                    \n                                An IndieWeb Podcast\n                            \n                                            \n                                        \n                                                    \n                        \n                                                    \n                                What I'm Reading\n                            \n                                            \n                                        \n                                                    \n                                                        \n                                    Need Help Publishing? \n                                \n                            \n                                            \n                                        \n                                                    \n                        \n                                                    \n                                Popular Science Books on Information Theory, Biology, and Complexity\n                            \n                                            \n                                        \n                                                    \n                        \n                                                    \n                                What is Information? by Christoph Adami\nA proper understanding of information in terms of prediction is key to a number of disciplines beyond engineering, such as physics and biology.\n                            \n                                            \n                                        \n                                                    \n                                                        \n                                    It's time to embrace open & disrupt social media\n                                \n                            \n                                                    \n                                Feed reader revolution\n                            \n                                            \n                        Syndicated copies to:",
        "html": "<p></p>\n<ul><li>\n<i></i>\u00a0<a title=\"Longerform content (Traditional blog)\" href=\"https://boffosocko.com/kind/article/\">Articles</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Status updates and short notes\" href=\"https://boffosocko.com/kind/note/\">Notes</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Replies to content on other sites\" href=\"https://boffosocko.com/kind/reply/\">Replies</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Photos\" href=\"https://boffosocko.com/kind/photo/\">Photos</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Places I've visited\" href=\"https://boffosocko.com/category/checkin/\">Checkins</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Audio files I've found interesting\" href=\"https://boffosocko.com/type/audio\">Audio</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"My short podcast episodes on various topics\" href=\"https://boffosocko.com/category/microcast/\">Microcast</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Podcasts and other audio I've listened to\" href=\"https://boffosocko.com/kind/listen/\">Listens</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Film, television, or videos I've watched\" href=\"https://boffosocko.com/kind/watch/\">Watches</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Events I've RSVPd to\" href=\"https://boffosocko.com/kind/rsvp/\">RSVPs</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Things I've actually read\" href=\"https://boffosocko.com/kind/read/\">Read</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Highlights from the web\" href=\"https://boffosocko.com/kind/highlight/\">Highlights</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Annotations from the web\" href=\"https://boffosocko.com/kind/annotation/\">Annotations</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Things I love\" href=\"https://boffosocko.com/kind/favorite/\">Favorites</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Content or creators I've enjoyed\" href=\"https://boffosocko.com/kind/like/\">Likes</a>\n</li>\n<li>\n<i></i>\u00a0<a href=\"https://boffosocko.com/kind/repost/\">Reposts</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Interesting things I'd like to revisit\" href=\"https://boffosocko.com/kind/bookmark/\">Bookmarks</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"People or Things I'm following or have subscribed to\" href=\"https://boffosocko.com/kind/follow/\">Follows</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Music that holds a special place in my heart\" href=\"https://boffosocko.com/kind/jam/\">Jams</a>\n</li>\n<li>\n<i></i>\u00a0<a href=\"https://boffosocko.com/type/video\">Video</a>\n</li>\n<li>\n<i></i>\u00a0<a href=\"https://boffosocko.com/type/quote/\">Quotes</a>\n</li>\n<li>\n<i></i>\u00a0<a href=\"https://boffosocko.com/type/chat/\">Chat</a>\n</li>\n<li>\n<i></i>\u00a0<a href=\"https://boffosocko.com/tag/recipe/\">Recipes</a>\n</li>\n<li>\n<i></i>\u00a0<a href=\"https://boffosocko.com/kind/eat/\">Eat</a>\n</li>\n<li>\n<i></i>\u00a0<a href=\"https://boffosocko.com/kind/drink/\">Drink</a>\n</li>\n<li>\n<i></i>\u00a0<a href=\"https://boffosocko.com/kind/exercise/\">Exercise</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Games played\" href=\"https://boffosocko.com/kind/play/\">Plays</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Chicken related posts\" href=\"https://boffosocko.com/kind/chicken/\">Chickens</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Itches\" href=\"https://boffosocko.com/kind/itch/\">Itches</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Issues filed to GitHub or other repositories\" href=\"https://boffosocko.com/kind/issue/\">Issues</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"My Wishlist\" href=\"https://boffosocko.com/kind/wish/\">Wishlist</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"Purchases, gifts, found things, or objects donated to me\" href=\"https://boffosocko.com/kind/acquisition/\">Acquisitions</a>\n</li>\n<li>\n</li><li>\n</li><li>\n</li></ul><ul><li>\n<i></i>\u00a0<a href=\"https://boffosocko.com/blog/\">Firehose</a>\n</li>\n<li>\n<i></i>\u00a0<a href=\"https://boffosocko.com/type/status\">Microblog</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"My Linkblog\" href=\"https://boffosocko.com/type/link/\">Linkblog</a>\n</li>\n<li>\n<i></i>\u00a0<a href=\"https://boffosocko.com/kind/eat,drink/\">Food Diary</a>\n</li>\n<li>\n<i></i>\u00a0<a title=\"An IndieWeb Podcast with David Shanske\" href=\"https://boffosocko.com/tag/an-indieweb-podcast/\">IndieWeb Podcast</a>\n</li>\n<li>\n</li></ul><p></p>\n\n\n<p>I use this <a title=\"Read more about our website philosophy and structure\" href=\"https://boffosocko.com/about/website-philosophy-structure\">website as my primary hub</a> for online presence and communication and to some extent as my online <a title=\"commonplace book | wikipedia\" href=\"https://en.wikipedia.org/wiki/Commonplace_book\">commonplace book</a>. I try to follow the tenets of the <a title=\"IndieWebCamp principles\" href=\"http://indiewebcamp.com/principles\">IndieWeb movement</a> by publishing on my own site and owning all of my own data. When I participate in social silos (Facebook, Twitter, Instagram, etc.), I post here first and syndicate duplicates out to them (<a title=\"POSSE (Post on your Own Site, Syndicate Elsewhere)\" href=\"http://indiewebcamp.com/POSSE\">POSSE</a>). These posts either originate from here or my <a href=\"http://stream.boffosocko.com/\">social stream</a>. You\u2019re welcome to subscribe to or consume them in any manner or on any platform you prefer.</p>\n<h2>Featured Posts</h2>\n\n\n\n        <ul><li>\n                        <a href=\"http://boffosocko.com/now/\">                            <img src=\"https://i2.wp.com/boffosocko.com/wp-content/uploads/2016/07/Right-Now.png?w=840&amp;ssl=1\" alt=\"What I'm up to\" /></a>\n                                                        \n                                    What I'm up to\n                                \n                            \n                                            </li>\n                                        <li>\n                        <a href=\"http://boffosocko.com/2017/07/28/an-introduction-to-the-indieweb/\">                            <img src=\"https://i1.wp.com/boffosocko.com/wp-content/uploads/2016/04/indie-web-camp-logo-thin-c-knockout-6.png?w=840&amp;ssl=1\" alt=\"An Introduction to the IndieWeb\" /></a>\n                                                        \n                                    An Introduction to the IndieWeb\n                                \n                            \n                                                    \n                                There's a better way to own and control your online identity\n                            \n                                            </li>\n                                        <li>\n                        <a href=\"https://boffosocko.com/research/indieweb/\">                            <img src=\"https://i1.wp.com/boffosocko.com/wp-content/uploads/2016/04/indie-web-camp-logo-thin-c-knockout-6.png?w=840&amp;ssl=1\" alt=\"A Collection of IndieWeb Articles\" /></a>\n                                                        \n                                    A Collection of IndieWeb Articles\n                                \n                            \n                                                    \n                                Here's a selection of articles and pieces I've written about IndieWeb related technology and philosophy.\n                            \n                                            </li>\n                                        <li>\n                        <a href=\"http://boffosockobooks.com/books/authors/henry-james-korn/amerikan-krazy/\">                            <img src=\"https://i1.wp.com/boffosocko.com/wp-content/uploads/2016/03/HJK-Amerikan-Krazy-1920x1080.jpg?resize=840%2C473&amp;ssl=1\" alt=\"\" /></a>\n                        \n                                            </li>\n                                        <li>\n                        <a href=\"https://boffosocko.com/category/podcast/\">                            <img src=\"https://i1.wp.com/boffosocko.com/wp-content/uploads/2018/03/IWC-Logo.png?w=840&amp;ssl=1\" alt=\"\" /></a>\n                        \n                                                    \n                                An IndieWeb Podcast\n                            \n                                            </li>\n                                        <li>\n                        <a href=\"https://boffosocko.com/kind/read/\">                            <img src=\"https://i1.wp.com/boffosocko.com/wp-content/uploads/2017/09/book-with-glasses.jpg?w=840&amp;ssl=1\" alt=\"\" /></a>\n                        \n                                                    \n                                What I'm Reading\n                            \n                                            </li>\n                                        <li>\n                        <a href=\"http://www.boffosocko.com/publishing\">                            <img src=\"https://i2.wp.com/boffosocko.com/wp-content/uploads/2014/09/boffo-socko-books-plate.jpg?w=840&amp;ssl=1\" alt=\"Need Help Publishing?\" /></a>\n                                                        \n                                    Need Help Publishing? \n                                \n                            \n                                            </li>\n                                        <li>\n                        <a href=\"http://boffosocko.com/2015/05/12/popular-science-books-on-information-theory-biology-and-complexity/\">                            <img src=\"https://i2.wp.com/boffosocko.com/wp-content/uploads/2016/01/pedigree_of_man_background_1600x1200.png?w=840&amp;ssl=1\" alt=\"\" /></a>\n                        \n                                                    \n                                Popular Science Books on Information Theory, Biology, and Complexity\n                            \n                                            </li>\n                                        <li>\n                        <a href=\"http://boffosocko.com/2016/01/27/what-is-information-by-christoph-adami/\">                            <img src=\"https://i0.wp.com/boffosocko.com/wp-content/uploads/2015/11/ChristophAdami.jpg?w=840&amp;ssl=1\" alt=\"\" /></a>\n                        \n                                                    \n                                What is Information? by Christoph Adami\nA proper understanding of information in terms of prediction is key to a number of disciplines beyond engineering, such as physics and biology.\n                            \n                                            </li>\n                                        <li>\n                        <a href=\"http://boffosocko.com/2017/06/09/how-feed-readers-can-grow-market-share-and-take-over-social-media/\">                            <img src=\"https://i0.wp.com/boffosocko.com/wp-content/uploads/2017/06/RSS-Head.png?w=840&amp;ssl=1\" alt=\"It's time to embrace open &amp; disrupt social media\" /></a>\n                                                        \n                                    It's time to embrace open &amp; disrupt social media\n                                \n                            \n                                                    \n                                Feed reader revolution\n                            \n                                            </li>\n                        </ul>\n\n<span>Syndicated copies to:</span><ul><li><a class=\"u-syndication\" href=\"https://chrisaldrich.wordpress.com/?p=55670253\"> </a></li></ul>"
    },
    "post-type": "note",
    "_id": "1756516",
    "_is_read": true
}`

**Comment by aaronpk** [comment]
I assume you've refreshed the page in monocle to check if they're gone? Monocle doesn't do any caching or storage itself, but also doesn't do anything real-time so it loads from Aperture in every page load.

**Comment by vipickering** [comment]
yes, I've refreshed multiple times and tried changing the cache. I also added a new channel, which appeared in Monocle to double check I am seeing "new" data.

**Comment by vipickering** [comment]
I think it might be related to the specific feed (https://boffosocko.com).

I've tried reproducing it with other feeds and it seems to work fine. But that one gets stuck everytime.

**Comment by aaronpk** [comment]
There was a different problem with that specific feed, which was causing all sorts of issues. It's been cleared up now though, can you tell if this is still an issue?

**Comment by vipickering** [comment]
Hi Aaron, just checked and it appears to have cleared feed

Thanks!
