### ISSUE TITLE
IndieAuth errors: too few arguments passed

### ISSUE THREAD

**Issue by janboddez** [aaronpk/Aperture#74]
Tried installing, then logging in and ran into `Too few arguments to function IndieAuth\Client::resolveMeURL(), 1 passed ... and exactly 4 expected` in `aperture/app/Http/Controllers/LoginController.php(33): IndieAuth\\Client::resolveMeURL('https://...')`. 'Solved' this by adding two empty objects as extra parameters. Can then proceed to GitHub (or whatever provider) to sign in.

Upon returning to my site, though, I get another error: `Too few arguments to function IndieAuth\Client::getAccessToken(), 5 passed ... and at least 6 expected`. In `aperture/app/Http/Controllers/LoginController.php` on line 100. Worked around this once more by passing an additional  empty `$codeVerifier` object.

Seems the IndieAuth package was updated but Aperture not changed accordingly.

**Comment by aaronpk** [comment]
Thanks, that's weird, I'll take a look. Definitely an issue with the wrong version of the indieauth client library.

**Comment by janboddez** [comment]
Hmm. I probably had at one point run `composer update` rather than stick with a default `composer install`, as it does not reoccur on a new instance.

**Comment by janboddez** [comment]
Reinstalled multiple times over and this hasn't reoccurred, so the above is almost certainly true.
